# Generated by Django 5.1.6 on 2025-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_remove_entry_category_entry_user_userbudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
