# Generated by Django 5.1.6 on 2025-04-29 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_entry_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbudget',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='userbudget',
            unique_together={('user', 'email')},
        ),
    ]
